// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TimeRegisterApp.Context;

namespace TimeRegisterApp.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220517114455_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TimeRegisterApp.Models.Checkpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("MarkedTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Checkpoints");
                });

            modelBuilder.Entity("TimeRegisterApp.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpentTimeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpentTimeId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TimeRegisterApp.Models.SpentTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SpentTimes");
                });

            modelBuilder.Entity("TimeRegisterApp.Models.Checkpoint", b =>
                {
                    b.HasOne("TimeRegisterApp.Models.Project", null)
                        .WithMany("Checkpoints")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TimeRegisterApp.Models.Project", b =>
                {
                    b.HasOne("TimeRegisterApp.Models.SpentTime", "SpentTime")
                        .WithMany("Projects")
                        .HasForeignKey("SpentTimeId");

                    b.Navigation("SpentTime");
                });

            modelBuilder.Entity("TimeRegisterApp.Models.Project", b =>
                {
                    b.Navigation("Checkpoints");
                });

            modelBuilder.Entity("TimeRegisterApp.Models.SpentTime", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
